
version: '3.2'

networks:
    hlf_multi_host_network:
        external: 
            name: hlf_multi_host_network

services:

    ca_org3:
        networks:
            hlf_multi_host_network:
                aliases:
                    - ca_org3
        extra_hosts:
            - "peer0.org3.example.com:172.31.58.209"
			- "peer1.org3.example.com:172.31.58.209"
        image: hyperledger/fabric-ca:amd64-1.4.4
        hostname: ca.org3.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org3
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/14adb1a8619a182f22db4046f1018dc4626dc0c2e1db202ffb5512201371f8f8_sk
        ports:
            - 9054:7054   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org3:
        extra_hosts:
            - "peer0.org3.example.com:172.31.58.209"
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb0_org3
        ports:
           - 9984:5984
        networks:
           - hlf_multi_host_network

    couchdb1_org3:
        extra_hosts:
            - "peer1.org3.example.com:172.31.58.209"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-32-21
                    - engine.labels.aws.region == us-east-2
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb1_org3
        ports:
           - 10984:5984
        networks:
           - hlf_multi_host_network
