
version: '3.2'

networks:
    hlf_multi_host_network:
        external: 
            name: hlf_multi_host_network

services:

    orderer_org3:
		extra_hosts:
			- "peer0.org1.example.com:172.31.8.85"
			- "peer1.org1.example.com:172.31.8.85"
			- "peer0.org2.example.com:172.31.39.243"
			- "peer1.org2.example.com:172.31.39.243"
			- "peer0.org3.example.com:172.31.32.21"
			- "peer1.org3.example.com:172.31.32.21"
			- "orderer1.example.com:172.31.8.85"
			- "orderer2.example.com:172.31.39.243"
        image: hyperledger/fabric-orderer:amd64-1.4.4
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        hostname: orderer3.example.com
        environment:
          - FABRIC_LOGGING_SPEC=INFO
          - ORDERER_HOST=orderer3.example.com
          - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
          - ORDERER_GENERAL_LISTENPORT=7050
          - ORDERER_GENERAL_GENESISMETHOD=file
          - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/channel-artifacts/genesis.block
          - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
          - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
          # enabled TLS
          - ORDERER_GENERAL_TLS_ENABLED=true
          - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
          - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
          - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
          - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
          - ORDERER_KAFKA_VERBOSE=true
          - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/tls/server.crt
          - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/tls/server.key
          - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/tls/ca.crt]
          - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8445  # operation RESTful API
          - ORDERER_METRICS_PROVIDER=prometheus  # prometheus will pull metrics from orderer via /metrics RESTful API
          - ORDERER_OPERATIONS_TLS_ENABLED=false
          - ORDERER_OPERATIONS_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
          - ORDERER_OPERATIONS_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
          - ORDERER_OPERATIONS_TLS_CLIENTROOTCAS=[/var/hyperledger/tls/ca.crt]
          - ORDERER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=false
        volumes:
            - /var/mynetwork/certs/crypto-config/ordererOrganizations/example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/channel-artifacts/:/var/hyperledger/channel-artifacts
        ports:
          - 9050:7050
          - 8445:8445
        networks:
          hlf_multi_host_network:
            aliases:
                - orderer3.example.com
